# Generated by Django 5.2.7 on 2025-10-29 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('education_level', models.CharField(choices=[('SIXTH_CLASS', 'Sixth_Class'), ('SEVENTH_CLASS', 'Seventh_Class'), ('EIGHTH_CLASS', 'Eighth_Class'), ('NINTH_CLASS', 'Ninth_Class'), ('TENTH_CLASS', 'Tenth_Class'), ('ELEVENTH_CLASS', 'Eleventh_Class'), ('TWELFTH_CLASS', 'Twelfth_Class')], max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'education_level',
            },
        ),
        migrations.CreateModel(
            name='ExamTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('exam_type', models.CharField(choices=[('JEE', 'Jee'), ('NEET', 'Neet'), ('MHTCET', 'Mhtcet'), ('WBJEE', 'Wbjee')], max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'exam_type',
            },
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(choices=[('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('MATHEMATICS', 'Mathematics'), ('BIOLOGY', 'Biology')], max_length=50)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tag_name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['tag_name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.TextField(null=True)),
                ('question_type', models.CharField(choices=[('SINGLE_SELECT', 'Single_Select'), ('MULTI_SELECT', 'Multi_Select'), ('NUMERIC', 'Numeric')], max_length=50)),
                ('marks', models.IntegerField(default=1)),
                ('negative_marks', models.IntegerField(default=0)),
                ('partial_marks', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=60)),
                ('difficulty_level', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('EXPERT', 'Expert')], max_length=50)),
                ('explanation', models.TextField(null=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_questions', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='questionbank.tagmodel')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='QuestionFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='question_files')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.questionmodel')),
            ],
            options={
                'db_table': 'question_file',
            },
        ),
        migrations.CreateModel(
            name='QuestionOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('option', models.TextField(null=True)),
                ('image', models.FileField(upload_to='question_option_image')),
                ('is_correct', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.questionmodel')),
            ],
            options={
                'db_table': 'question_option',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('answer', models.TextField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.questionmodel')),
                ('multi_select_answer', models.ManyToManyField(blank=True, related_name='multi_select_answer', to='questionbank.questionoptionmodel')),
                ('single_select_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_select_answer', to='questionbank.questionoptionmodel')),
            ],
            options={
                'db_table': 'question_answer',
            },
        ),
        migrations.CreateModel(
            name='ChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('chapter_name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionbank.subjectmodel')),
            ],
            options={
                'db_table': 'chapter',
                'ordering': ['chapter_name'],
            },
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('topic_name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionbank.chaptermodel')),
            ],
            options={
                'db_table': 'topic',
                'ordering': ['topic_name'],
            },
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionbank.topicmodel'),
        ),
    ]
